# Generated by Django 4.1.10 on 2025-12-23 09:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменен')),
                ('sort_ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
                ('image', models.ImageField(upload_to='catalog/images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog_app.good', verbose_name='Товар')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog_app.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='preview_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.image', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='good',
            name='preview_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.image', verbose_name='Превью'),
        ),
    ]
