# Generated by Django 4.1.10 on 2026-02-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.vat', verbose_name='Ставка НДС'),
        ),
    ]
