# Generated by Django 4.1.10 on 2025-12-11 10:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0002_client_email'),
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('number', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Номер')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='client_app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменен')),
                ('sort_ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Сумма')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.good', verbose_name='Номенклатура')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_app.order', verbose_name='Строки')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order_app.statusorder', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wish', to='client_app.client', verbose_name='Клиент')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.good', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Строка избранного',
                'verbose_name_plural': 'Избранное',
                'unique_together': {('client', 'good')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True, verbose_name='Количество')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='client_app.client', verbose_name='Клиент')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.good', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Строка корзины',
                'verbose_name_plural': 'Корзина',
                'unique_together': {('client', 'good')},
            },
        ),
    ]
