# Generated by Django 4.1.10 on 2025-12-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusorder',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Флаг закрытого заказа'),
        ),
    ]
