# Generated by Django 4.1.10 on 2025-12-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_client_email'),
        ('order_app', '0002_statusorder_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='client_app.client', verbose_name='Клиент'),
        ),
    ]
