# Generated by Django 4.1.10 on 2026-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_orderitem_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Сумма, без НДС'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена, без НДС'),
        ),
    ]
