# Generated by Django 4.1.10 on 2026-02-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_orderitem_amount_without_vat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='amount_without_vat',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_without_vat',
        ),
    ]
