# Generated by Django 4.1.10 on 2026-02-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_good_vat'),
        ('order_app', '0007_remove_orderitem_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.vat', verbose_name='Ставка НДС'),
        ),
    ]
