# Generated by Django 4.1.10 on 2026-02-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('const_app', '0002_vat_alter_const_vat'),
        ('order_app', '0008_orderitem_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='const_app.vat', verbose_name='Ставка НДС'),
        ),
    ]
