# Generated by Django 4.1.10 on 2026-02-27 03:56

from django.db import migrations, models
import django.db.models.deletion
import repositories.const_repository


class Migration(migrations.Migration):

    dependencies = [
        ('const_app', '0002_vat_alter_const_vat'),
        ('order_app', '0009_alter_orderitem_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='possible_date',
            field=models.DateField(null=True, verbose_name='Возможная дата'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='required_date',
            field=models.DateField(null=True, verbose_name='Требуемая дата'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='possible_date',
            field=models.DateField(null=True, verbose_name='Возможная дата'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='required_date',
            field=models.DateField(null=True, verbose_name='Требуемая дата'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vat',
            field=models.ForeignKey(blank=True, default=repositories.const_repository.fetch_last_vat, null=True, on_delete=django.db.models.deletion.PROTECT, to='const_app.vat', verbose_name='Ставка НДС'),
        ),
    ]
