# Generated by Django 4.1.10 on 2026-02-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0010_cartitem_possible_date_cartitem_required_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusorder',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Статус доступен для заказчика'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='possible_date',
            field=models.DateField(blank=True, null=True, verbose_name='Возможная дата'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='required_date',
            field=models.DateField(blank=True, null=True, verbose_name='Требуемая дата'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='possible_date',
            field=models.DateField(blank=True, null=True, verbose_name='Возможная дата'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='required_date',
            field=models.DateField(blank=True, null=True, verbose_name='Требуемая дата'),
        ),
    ]
