# Generated by Django 4.1.10 on 2026-02-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0011_statusorder_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sap_number',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Номер заказа из программы SAP'),
        ),
    ]
