# Generated by Django 4.1.10 on 2026-02-26 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('const_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменен')),
                ('sort_ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Ставка НДС',
                'verbose_name_plural': 'Ставки НДС',
            },
        ),
        migrations.AlterField(
            model_name='const',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='const_app.vat', verbose_name='Ставка НДС'),
        ),
    ]
