# Generated by Django 4.1.10 on 2025-12-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=150, unique=True, verbose_name='Адрес эл.почты'),
        ),
    ]
